### ISSUE TITLE
Is AVTK portable?

### ISSUE THREAD

**Issue by unfa** [harryhaaren/openAV-AVTK#10]
Can plugins based on AVTK run on Linux, Windows and Mac?

I'm stating to care about my Windows-running folks who are switching to FLOSS for music production :)

**Comment by harryhaaren** [comment]
Hey unfa, Yes in theory it is. I've had screenshots sent to me of various AVTK screens with MacOS window borders, not so sure about Win32/Win64. In short - there is no reason why it would not work - it just needs some time to set-up. Biggest problem for me as a developer is that I don't currently (and haven't had in the last years) have access to a MacOS or Windows machine... so literally can't try/test it.

Please note this image below was sent to me, with the following quote:

> it just worked without touching any CMake file. I guess that all the dependencies were already installed when I was trying to get NTK compiled (I just used brew install, a package manager for OSX similar to apt-get).

<img width="813" alt="screen shot 2017-01-07 at 16 12 42" src="https://user-images.githubusercontent.com/106664/30567109-bc6f652c-9cc6-11e7-84c0-97a42b98a2cd.png">

**Comment by harryhaaren** [comment]
Cleaning up, so closing this
