### ISSUE TITLE
widgetValueCB

### ISSUE THREAD

**Issue by ssj71** [harryhaaren/openAV-AVTK#6]
Hey Harry,

so I see that we're required to overload widgetValueCB(), but it looks like it yeilds some pretty burly if-else-if trees:
https://github.com/openAVproductions/openAV-Fabla2/blob/master/src/ui/fabla2_ui.cxx#L1184

Why aren't callbacks per widget? 
are there any simpler examples for AVTK? fabla2 and even the testUI in this repo are rather sophisticated.

**Comment by harryhaaren** [comment]
Hey Ssj71,

Callbacks can be per widget. I don't like too many functions either, although I agree that the Fabla2 ui has grown out of control : )

For more (reasonable) examples, see:
https://github.com/openAVproductions/openAV-AVTK/blob/master/test_ui.cxx#L248
https://github.com/openAVproductions/openAV-ArtyFX/blob/avtk/src/ui/roomy.cxx#L31

If you like, I can do up a minimal example with a callback function for each widget on the UI? I think you're well able to figure that part out yourself too though?

```
static void custom_widget_callback(Avtk::Widget* w, void* ud)
{
    printf("%s : %s has %f\n", __func__, w->label(), w->value());
}
```

```
Class UI
{
Avtk::Button* custom = new Avtk::Button( this, 250, 20, 150, 200, "Custom CB" );
custom->callback   = custom_widget_callback;
custom->callbackUD = this;
}
```

That's all there is to it :) Again - if you think an example showing this commited in the repo would be useful, just say! Cheers, -Harry

**Comment by ssj71** [comment]
ah I looked at artyfx, but at the wrong branch. Thanks!
